### ISSUE TITLE
Handle umbrella projects

### ISSUE THREAD

**Issue by adamzapasnik** [adamzapasnik/vscode-elixir-test-explorer#1]
Get them from apps folder and create `ExUnit` instance for each separately? 

For now `projectDir` can be used as a quick half-fix.

ETA Next Friday/Weekend :sweat:

**Comment by bengro** [comment]
I'm coming from intellij to VS code .. I would so love this plugin! :)

Unfortunately, it doesn't work for my umbrella project.

**Comment by adamzapasnik** [comment]
Yea, I have a wip branch somewhere for it, but I haven't had time to work on it :sweat:

**Comment by bengro** [comment]
I started working on this ... it's a pretty big change. If you have some advice or tips for me, I'd appreciate it.

As I'm adding tests I'm restructuring the project a little - I hope that's ok.

**Comment by adamzapasnik** [comment]
Great :) as long as it works it's perfectly fine :+1: I don't really care about the project structure much, it's far from perfect.

Here is the branch with some tentative changes https://github.com/adamzapasnik/vscode-elixir-test-explorer/compare/umbrella-wip?expand=1 But to best honest, I couldn't figure out a good solution, so I feel free to come up with your own solution.

**Comment by adamzapasnik** [comment]
Has been released. Big bravo to @bengro  :)
