### ISSUE TITLE
Feature request: filtering results by their state

### ISSUE THREAD

**Issue by fbettag** [adamzapasnik/vscode-elixir-test-explorer#11]
I have a couple of projects with 1000+ tests and it's a little bit hard to scroll to where it's breaking. In IntelliJ they have this nice feature to filter tests by state, so basically i can set it "only show failed" to only see the relevant things failing.

This would make a great addition imho.

also, thanks for this great plugin! :)

**Comment by adamzapasnik** [comment]
hey @fbettag, this is possible if you configure the testExplorer extension to use the native vscode API `"testExplorer.useNativeTesting": true`
<img width="419" alt="Screenshot 2022-09-08 at 07 39 18" src="https://user-images.githubusercontent.com/9281806/189035644-014bfaef-6b15-44ad-95e8-9b26c685c5ca.png">
