### ISSUE TITLE
--only : Missing argument of type keep

### ISSUE THREAD

**Issue by michal-turzynski** [adamzapasnik/vscode-elixir-test-explorer#14]
Hi @adamzapasnik, first of all - huge thanks for the extension 😊 

I am experiencing the following problem when the extension loads test cases:

![image](https://user-images.githubusercontent.com/284403/167805955-5002fb3f-c1d1-4869-91c6-dc63bf65955a.png)

Output:
```
** (Mix) Could not invoke task "test": 1 error found!
--only : Missing argument of type keep
``` 

Also, when I execute the following command `mix test --trace --seed=0 --only=""`, I get exactly same result.

The following command works just fine though:
`mix test --trace --seed=0 --only="___"`  ( "_" could be replaced with something else that wouldn't match any tests, e.g. ! or *)
Result of the above command:
```
Finished in 0.2 seconds (0.2s async, 0.00s sync)
51 tests, 0 failures, 51 excluded
```

My versions:
```
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
Elixir 1.13.4 (compiled with Erlang/OTP 22)
```

Any ideas what might be wrong here?

**Comment by Janekdererste** [comment]
I am experiencing the same issue.

**Comment by michal-turzynski** [comment]
@adamzapasnik, any chance to look at the above PR with a workaround? If I can help somehow, please let me know.

**Comment by adamzapasnik** [comment]
I've published the fix, let me know if it's fixed and I'll close this issue. Thank you for help :)

**Comment by michal-turzynski** [comment]
Thanks @adamzapasnik. I had to push one more change for the tests parser component as the output changed slightly 
https://github.com/adamzapasnik/vscode-elixir-test-explorer/pull/19

also, this is related https://github.com/adamzapasnik/vscode-elixir-test-explorer/pull/18

**Comment by MicheleTogni** [comment]
Hello @adamzapasnik
As @michal-turzynski mentioned, i have opened #18 that seems to overlap with this issue; i didn't think it had to do with this one because the output error is different, but seeing the fix made by @michal-turzynski it looks like it could be useful for both

**Comment by adamzapasnik** [comment]
Apologies for the problem, seems I forgot to test the change before the release 😓 

A new version is out, thanks for the fix @MicheleTogni

**Comment by MicheleTogni** [comment]
Glad to be helpful; thank you for your useful extension!
