### ISSUE TITLE
Adapter fails if there are warnings

### ISSUE THREAD

**Issue by jonathanstiansen** [adamzapasnik/vscode-elixir-test-explorer#2]
Hey! Thanks for making this, we desperately need this in the elixir world!

I'm having an issue which I think is unintended. Whenever there are any warnings in my code, it doesn't find any tests. It returns a error on the discovery part of the testing:

```
Command failed: mix test --trace --seed=0 --only="" 
warning: variable "owner" is unused (if the variable is not meant to be used, prefix it with an underscore)
  test/myapp/my_test.exs:37: MyApp.MyTest."test anything"/1

The --only option was given to "mix test" but no test was executed
```

The testing pane doesn't show any tests at this point, just `ExUnit:Error` when I remove the warning it works.

**Comment by adamzapasnik** [comment]
Hi, thanks for the kind words.

I was able to reproduce this silly bug. Unfortunately, I will fix it after adding umbrella support. (Probably the next month :sweat:)

**Comment by jonathanstiansen** [comment]
No problem! I can deal in the meantime 😄

**Comment by bengro** [comment]
See, https://github.com/adamzapasnik/vscode-elixir-test-explorer/pull/4

**Comment by adamzapasnik** [comment]
A new version is available with the fix. Thanks a lot to @bengro.

Closing this, but @jonathanstiansen feel free to open a new one if it's still broken.
